const INITIAL_BALANCE = 1000;
const MIN_BET = 10;
const DEALER_HIT_THRESHOLD = 17;
const BLACKJACK_PAYOUT = 1.5;
const REGULAR_WIN_PAYOUT = 1.0;
const INSURANCE_PAYOUT = 2.0;
const DECK_COUNT = 1;

export {
  INITIAL_BALANCE,
  MIN_BET,
  DEALER_HIT_THRESHOLD,
  BLACKJACK_PAYOUT,
  REGULAR_WIN_PAYOUT,
  INSURANCE_PAYOUT,
  DECK_COUNT
};
